project:
  type: website
  output-dir: docs   # GitHub Pages can serve from /docs on the main branch

website:
  title: "Diego Olivares"
  description: "Researcher | DPhil candidate, Oxford Internet Institute"
  site-url: "https://diegolivaresm.github.io"   # adjust if you use a custom domain
  favicon: assets/favicon.png

  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: experience.qmd
        text: Experience
    right:
      - icon: github
        href: https://github.com/diegolivaresm
        aria-label: GitHub
      - text: "ORCID"
        href: https://orcid.org/0009-0008-4754-5442   # <-- replace with your ORCID
        aria-label: ORCID
      - text: "Dataverse"
        href: https://dataverse.harvard.edu/dataverse/diego_olivares  # <-- adjust
        aria-label: Harvard Dataverse
      - icon: envelope
        href: "mailto:diego.olivares@alumni.uc.cl"          # <-- replace
        aria-label: Email
      - icon: linkedin
        href: https://www.linkedin.com/in/diego-olivares-009ab22b0/
        aria-label: LinkedIn

  page-footer:
    left: "© 2026 Diego Olivares"
    right: "Built with [Quarto](https://quarto.org)"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    css: styles.css
    page-layout: full
validate-yaml: false 